### ISSUE TITLE
App crash on try to add ppl (tag friend)

### ISSUE THREAD

**Issue by MrThiago** [chiuki/friendspell#3]
whenever I try to app a friend (tag friend) the App crashes. Same thing happen to the version downloaded from playStore

**Comment by chiuki** [comment]
Can you post a stack trace? Thanks!

**Comment by eduardb** [comment]
This must be the crash @MrThiago mentioned:

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.google.android.gms.plus.model.people.Person.getId()' on a null object reference
  at com.sqisland.friendspell.api.GoogleApiClientBridge.getCurrentPerson(GoogleApiClientBridge.java:83)
  at com.sqisland.friendspell.activity.BaseNearbyActivity.publishAndSubscribe(BaseNearbyActivity.java:224)
  at com.sqisland.friendspell.activity.BaseNearbyActivity.onConnected(BaseNearbyActivity.java:177)
  at com.google.android.gms.common.internal.zzk.zzk(Unknown Source)
  at com.google.android.gms.internal.zzmg.zzi(Unknown Source)
  at com.google.android.gms.internal.zzme.zzpi(Unknown Source)
  at com.google.android.gms.internal.zzme.onConnected(Unknown Source)
  at com.google.android.gms.internal.zzmi.onConnected(Unknown Source)
  at com.google.android.gms.internal.zzlz.onConnected(Unknown Source)
  at com.google.android.gms.common.internal.zzj$zzg.zzqv(Unknown Source)
  at com.google.android.gms.common.internal.zzj$zza.zzc(Unknown Source)
  at com.google.android.gms.common.internal.zzj$zza.zzv(Unknown Source)
  at com.google.android.gms.common.internal.zzj$zzc.zzqx(Unknown Source)
  at com.google.android.gms.common.internal.zzj$zzb.handleMessage(Unknown Source)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5254)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

And it's caused by these two lines of code:

```
    Person person = Plus.PeopleApi.getCurrentPerson(googleApiClient);
    profileImages.put(person.getId(), getProfileImageUrl(person));
```

`person` is null probably since the `PeopleApi.getCurrentPerson()` method has been deprecated. I'll come back with a pull request containing a migration to the new Google Sign In API that will resolve this problem as well.
